### ISSUE TITLE
This model's maximum context length is 128000 tokens. However, your messages resulted in 271344 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by XinshaoAmosWang** [yongliang-wu/MM-VID#2]
Hi @yongliang-wu , 

Thanks for providing the details about how to reproduce your great work, I followed your guide to run the multiple steps. 

In the final step, to generate the coherent script, I got the following error: 

`
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 128000 tokens. However, your messages resulted in 271344 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
`

Do you have suggestion on how to solve this issue? 

Thanks very much in advance. 
Best regards, 
Amos

**Comment by yongliang-wu** [comment]
Thank you for proposing the issue. I think one straight forward way to solve this problem is to reduce the sampling frame when generating clip-level descriptions

**Comment by yongliang-wu** [comment]
Thank you for highlighting this issue. One straightforward solution is to reduce the sampling frame when generating clip-level descriptions. You can modify line 140 to use a smaller number, such as 3. Alternatively, you could use a model that supports a longer context length.

```python
    # Step 4: Generate Clip Descriptions
    clip_descriptions = generate_clip_descriptions(clip_paths, scenes, 3)
    print("Clip Descriptions:", clip_descriptions)
```
